/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pos.GUI;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author NEVALUV
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLoginForm = new javax.swing.JPanel();
        panelLoginInput = new javax.swing.JPanel();
        panelLoginInputCenter = new javax.swing.JPanel();
        panelUsername = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        panelPassword = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        cbRememberThisAccount = new javax.swing.JCheckBox();
        panelLoginButton = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        panelWelcome = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        panelViewImage = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("LoginFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);

        panelLoginForm.setBackground(new java.awt.Color(153, 204, 255));
        panelLoginForm.setPreferredSize(new java.awt.Dimension(320, 0));
        panelLoginForm.setLayout(new java.awt.BorderLayout());

        panelLoginInput.setBackground(new java.awt.Color(153, 204, 255));
        panelLoginInput.setMinimumSize(new java.awt.Dimension(320, 100));
        panelLoginInput.setLayout(new java.awt.GridBagLayout());

        panelLoginInputCenter.setBackground(new java.awt.Color(153, 204, 255));
        panelLoginInputCenter.setPreferredSize(new java.awt.Dimension(320, 200));

        panelUsername.setBackground(new java.awt.Color(153, 204, 255));
        panelUsername.setPreferredSize(new java.awt.Dimension(248, 52));
        panelUsername.setLayout(new java.awt.BorderLayout(4, 4));

        lblUsername.setText("Username");
        panelUsername.add(lblUsername, java.awt.BorderLayout.NORTH);
        panelUsername.add(txtUsername, java.awt.BorderLayout.CENTER);

        panelLoginInputCenter.add(panelUsername);

        panelPassword.setBackground(new java.awt.Color(153, 204, 255));
        panelPassword.setPreferredSize(new java.awt.Dimension(248, 52));
        panelPassword.setLayout(new java.awt.BorderLayout(4, 4));

        lblPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        panelPassword.add(lblPassword, java.awt.BorderLayout.NORTH);
        panelPassword.add(txtPassword, java.awt.BorderLayout.CENTER);

        panelLoginInputCenter.add(panelPassword);

        cbRememberThisAccount.setText("Remember this account?");
        cbRememberThisAccount.setPreferredSize(new java.awt.Dimension(248, 32));
        panelLoginInputCenter.add(cbRememberThisAccount);

        panelLoginButton.setBackground(new java.awt.Color(153, 204, 255));
        panelLoginButton.setPreferredSize(new java.awt.Dimension(248, 36));
        panelLoginButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setText("Login");
        btnLogin.setPreferredSize(new java.awt.Dimension(80, 24));
        panelLoginButton.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 6, -1, -1));

        panelLoginInputCenter.add(panelLoginButton);

        panelLoginInput.add(panelLoginInputCenter, new java.awt.GridBagConstraints());

        panelLoginForm.add(panelLoginInput, java.awt.BorderLayout.CENTER);

        panelWelcome.setBackground(new java.awt.Color(153, 204, 255));
        panelWelcome.setMinimumSize(new java.awt.Dimension(320, 100));
        panelWelcome.setLayout(new java.awt.BorderLayout());

        lblWelcome.setBackground(new java.awt.Color(153, 204, 255));
        lblWelcome.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("WELCOME");
        lblWelcome.setPreferredSize(new java.awt.Dimension(320, 100));
        panelWelcome.add(lblWelcome, java.awt.BorderLayout.CENTER);

        panelLoginForm.add(panelWelcome, java.awt.BorderLayout.NORTH);

        getContentPane().add(panelLoginForm, java.awt.BorderLayout.WEST);

        panelViewImage.setBackground(new java.awt.Color(255, 255, 255));
        panelViewImage.setLayout(new java.awt.GridBagLayout());

        lblLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/posLogo.png"))); // NOI18N
        panelViewImage.add(lblLogo, new java.awt.GridBagConstraints());

        getContentPane().add(panelViewImage, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, UnsupportedLookAndFeelException {
try {
    UIManager.setLookAndFeel( new FlatLightLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox cbRememberThisAccount;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panelLoginButton;
    private javax.swing.JPanel panelLoginForm;
    private javax.swing.JPanel panelLoginInput;
    private javax.swing.JPanel panelLoginInputCenter;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel panelUsername;
    private javax.swing.JPanel panelViewImage;
    private javax.swing.JPanel panelWelcome;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
